CREATE TABLE "GCG_4418_SO"(
 "AUTONUM" IDENTITY DEFAULT '0',
 "CUSTOMER" CHAR(6),
 "PART" CHAR(17),
 "DESCRIPTION" CHAR(30),
 "REV" CHAR(3),
 "PRICE" NUMERIC(14,2),
 "PO_NUM" CHAR(15),
 "DUE_DATE" CHAR(6),
 "ORDER_QTY" NUMERIC(14,2),
 "ORDER_PLACED" CHAR(6),
 "SEQ" INTEGER,
 UNIQUE ("AUTONUM"));